FROM golang:latest

# Install sqlc
RUN go install github.com/sqlc-dev/sqlc/cmd/sqlc@latest

# Install goose
RUN go install github.com/pressly/goose/v3/cmd/goose@latest

# Set the working directory inside the container
WORKDIR /app

# Uncomment the following line to keep the container running
# CMD tail -f /dev/null
